language: node_js
node_js:
- '0.10'
before_script:
- npm install -g codeclimate-test-reporter
- npm install --loglevel warn
after_script:
- codeclimate < test/coverage/aqa/lcov.info
env:
  global:
    secure: tsipXq8wv3G0ySgaxUWzCdpvEGXW6ZNe+bXpzHeMCp2I2jQZuLEZgmDzqBYqotCKi0aFG+lIyYqaGAKIXboXyGFCXcuMRd+D4hxP1gYvcgEiCZzUYykTFgxYKN9pgMHjVBNZgPr/PUDYsIM/9K8jd6HXR9V+NKM+G3fPs7szBsU=
