language: node_js
node_js:
- '0.10'
before_script:
- npm install -g codeclimate-test-reporter
- npm install --loglevel warn
env:
  global:
    secure: ZUObSi7w2oGxKWi4sRT6AmhYzAjrVXByIT49x0Coi6eXf+XzOpYILGHyhVvwCnHHS1vKt+vWfFZIXhp8BR94amj+0dZ0on56Mi1wgaZB9dLqZBuaXHthbJEYJvOh/4NWxPnQ4aHxAQRYDdWfMf7y1cpju3bigNZvFJd1WYHt8eE=